### ISSUE TITLE
Not possible to install examples project

### ISSUE THREAD

**Issue by mkovacek** [adobe/aem-angular-core-wcm-components#10]
Hi, it's not possible to install examples project 

➜  examples git:(master) mvn clean install -PautoInstallSinglePackage -PautoInstallPackage -Pclassic

https://gist.github.com/mkovacek/b1cd9e0aa4df609e5aea5fc967d85c37

**Comment by mkovacek** [comment]
Found solution.
In _package.json_ of _angular-spacomponents-example-project_ I need to change _aem-core-components-angular-spa_ and _aem-core-components-angular-base_ from file to the real one available in npm repository. 
Since ng build didn't create _aem-angular-core-spa-wcm-components_  in _dist_ folder

**Comment by niekraaijmakers** [comment]
Did you build the full project? From the reactor level? It should generate these files in there.
If it doesn't, we got a bug.

Reason being is we want to be able to develop these components and see the changes in your local project without npm link.

**Comment by mkovacek** [comment]
My bad, I guess I build inside /examples (core.wcm.components.angular.examples.reactor), and not in root (core.wcm.components.angular.reactor).
Works fine.
